// GENERATED by scripts/build-icons.mjs from ../foundations/ions-icons-inline.js
// Do not edit by hand; re-run `npm run build:icons` instead.

export interface IonIconDef {
  viewBox: string;
  body: string;
}

export const ionIcons = {
  "ion-arrow-back": {
    "viewBox": "0 0 24 24",
    "body": "<path d=\"M19 12H5m6-6-6 6 6 6\"/>"
  },
  "ion-arrow-forward": {
    "viewBox": "0 0 24 24",
    "body": "<path d=\"M5 12h14m-6-6 6 6-6 6\"/>"
  },
  "ion-chevron-down": {
    "viewBox": "0 0 24 24",
    "body": "<path d=\"m6 9 6 6 6-6\"/>"
  },
  "ion-chevron-up": {
    "viewBox": "0 0 24 24",
    "body": "<path d=\"m6 15 6-6 6 6\"/>"
  },
  "ion-close": {
    "viewBox": "0 0 24 24",
    "body": "<path d=\"m6 6 12 12M18 6 6 18\"/>"
  },
  "ion-menu": {
    "viewBox": "0 0 24 24",
    "body": "<path d=\"M4 7h16M4 12h16M4 17h16\"/>"
  },
  "ion-more": {
    "viewBox": "0 0 24 24",
    "body": "<circle cx=\"5\" cy=\"12\" r=\"1\"/><circle cx=\"12\" cy=\"12\" r=\"1\"/><circle cx=\"19\" cy=\"12\" r=\"1\"/>"
  },
  "ion-search": {
    "viewBox": "0 0 24 24",
    "body": "<circle cx=\"11\" cy=\"11\" r=\"6.5\"/><path d=\"m16 16 4 4\"/>"
  },
  "ion-calendar": {
    "viewBox": "0 0 24 24",
    "body": "<rect x=\"3.5\" y=\"5\" width=\"17\" height=\"15\" rx=\"2\"/><path d=\"M8 3v4M16 3v4M3.5 9.5h17\"/>"
  },
  "ion-location": {
    "viewBox": "0 0 24 24",
    "body": "<path d=\"M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0Z\"/><circle cx=\"12\" cy=\"10\" r=\"2.25\"/>"
  },
  "ion-swap": {
    "viewBox": "0 0 24 24",
    "body": "<path d=\"M7 5v14m0-14L4 8m3-3 3 3M17 19V5m0 14 3-3m-3 3-3-3\"/>"
  },
  "ion-bus": {
    "viewBox": "0 0 24 24",
    "body": "<rect x=\"5\" y=\"3.5\" width=\"14\" height=\"16\" rx=\"3\"/><path d=\"M7 7h10v6H7zM8 19.5V21m8-1.5V21M7.5 16h.01m8.99 0h.01\"/>"
  },
  "ion-filter": {
    "viewBox": "0 0 24 24",
    "body": "<path d=\"M4 6h16M7 12h10m-7 6h4\"/>"
  },
  "ion-sort": {
    "viewBox": "0 0 24 24",
    "body": "<path d=\"M8 4v16m0-16L4.5 7.5M8 4l3.5 3.5M16 20V4m0 16-3.5-3.5M16 20l3.5-3.5\"/>"
  },
  "ion-star": {
    "viewBox": "0 0 24 24",
    "body": "<path d=\"m12 3 2.7 5.5 6.1.9-4.4 4.3 1 6.1-5.4-2.9-5.4 2.9 1-6.1-4.4-4.3 6.1-.9L12 3Z\"/>"
  },
  "ion-info": {
    "viewBox": "0 0 24 24",
    "body": "<circle cx=\"12\" cy=\"12\" r=\"9\"/><path d=\"M12 10.5V17M12 7h.01\"/>"
  },
  "ion-check": {
    "viewBox": "0 0 24 24",
    "body": "<path d=\"m5 12.5 4.5 4.5L19 7.5\"/>"
  },
  "ion-check-circle": {
    "viewBox": "0 0 24 24",
    "body": "<circle cx=\"12\" cy=\"12\" r=\"9\"/><path d=\"m7.5 12 3 3 6-6\"/>"
  },
  "ion-error": {
    "viewBox": "0 0 24 24",
    "body": "<circle cx=\"12\" cy=\"12\" r=\"9\"/><path d=\"M12 7v6M12 17h.01\"/>"
  },
  "ion-plus": {
    "viewBox": "0 0 24 24",
    "body": "<path d=\"M12 5v14M5 12h14\"/>"
  },
  "ion-minus": {
    "viewBox": "0 0 24 24",
    "body": "<path d=\"M5 12h14\"/>"
  },
  "ion-edit": {
    "viewBox": "0 0 24 24",
    "body": "<path d=\"m4 20 4.5-1 10-10a2.1 2.1 0 0 0-3-3l-10 10L4 20Z\"/><path d=\"m14.5 7 3 3\"/>"
  },
  "ion-delete": {
    "viewBox": "0 0 24 24",
    "body": "<path d=\"M5 7h14M9 7V4h6v3m2 0-1 14H8L7 7m3 4v6m4-6v6\"/>"
  },
  "ion-home": {
    "viewBox": "0 0 24 24",
    "body": "<path d=\"m3 11 9-8 9 8M5.5 9.5V21h13V9.5M9.5 21v-7h5v7\"/>"
  },
  "ion-home-filled": {
    "viewBox": "0 0 24 24",
    "body": "<path d=\"M3 11.2 12 3l9 8.2-1.5 1.7-1-.9v9H14v-6h-4v6H5.5v-9l-1 .9L3 11.2Z\" fill=\"currentColor\" stroke=\"none\"/>"
  },
  "ion-ticket": {
    "viewBox": "0 0 24 24",
    "body": "<path d=\"M4 7a2 2 0 0 0 0 4v6h16v-6a2 2 0 0 0 0-4V5H4v2Z\"/><path d=\"M12 5v2m0 4v2m0 2v2\"/>"
  },
  "ion-bookings": {
    "viewBox": "0 0 24 24",
    "body": "<rect x=\"4\" y=\"3.5\" width=\"16\" height=\"17\" rx=\"2\"/><path d=\"m7 8 1.5 1.5L11 7M13 8.5h4M7 14l1.5 1.5L11 13m2 1.5h4\"/>"
  },
  "ion-offer": {
    "viewBox": "0 0 24 24",
    "body": "<path d=\"M4 5h10l6 6-9 9-7-7V5Z\"/><circle cx=\"8\" cy=\"9\" r=\"1.25\"/><path d=\"m11 15 4-4M11.5 11.5h.01M14.5 14.5h.01\"/>"
  },
  "ion-help": {
    "viewBox": "0 0 24 24",
    "body": "<path d=\"M4 5.5h16v11H9l-5 3v-14Z\"/><path d=\"M9.7 9a2.4 2.4 0 0 1 4.6 1c0 1.7-2.3 1.8-2.3 3.2M12 15.3h.01\"/>"
  },
  "ion-user": {
    "viewBox": "0 0 24 24",
    "body": "<circle cx=\"12\" cy=\"8\" r=\"4\"/><path d=\"M4.5 21a7.5 7.5 0 0 1 15 0\"/>"
  },
  "ion-account-circle": {
    "viewBox": "0 0 24 24",
    "body": "<circle cx=\"12\" cy=\"12\" r=\"9\"/><circle cx=\"12\" cy=\"9\" r=\"2.75\"/><path d=\"M7.5 18a5 5 0 0 1 9 0\"/>"
  },
  "ion-eye": {
    "viewBox": "0 0 24 24",
    "body": "<path d=\"M2.5 12S6 6.5 12 6.5 21.5 12 21.5 12 18 17.5 12 17.5 2.5 12 2.5 12Z\"/><circle cx=\"12\" cy=\"12\" r=\"2.5\"/>"
  },
  "ion-eye-off": {
    "viewBox": "0 0 24 24",
    "body": "<path d=\"m4 4 16 16M9.8 7A7.8 7.8 0 0 1 12 6.5c6 0 9.5 5.5 9.5 5.5a17 17 0 0 1-2.4 2.8M6.3 8.2A17 17 0 0 0 2.5 12S6 17.5 12 17.5a8 8 0 0 0 2.5-.4\"/>"
  },
  "ion-copy": {
    "viewBox": "0 0 24 24",
    "body": "<rect x=\"8\" y=\"8\" width=\"12\" height=\"12\" rx=\"2\"/><path d=\"M16 8V6a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h2\"/>"
  }
} as const satisfies Record<string, IonIconDef>;

/** Every icon id shipped by the Ions catalogue. */
export type IonIconName = keyof typeof ionIcons;

export const ionIconNames = [
  "ion-arrow-back",
  "ion-arrow-forward",
  "ion-chevron-down",
  "ion-chevron-up",
  "ion-close",
  "ion-menu",
  "ion-more",
  "ion-search",
  "ion-calendar",
  "ion-location",
  "ion-swap",
  "ion-bus",
  "ion-filter",
  "ion-sort",
  "ion-star",
  "ion-info",
  "ion-check",
  "ion-check-circle",
  "ion-error",
  "ion-plus",
  "ion-minus",
  "ion-edit",
  "ion-delete",
  "ion-home",
  "ion-home-filled",
  "ion-ticket",
  "ion-bookings",
  "ion-offer",
  "ion-help",
  "ion-user",
  "ion-account-circle",
  "ion-eye",
  "ion-eye-off",
  "ion-copy"
] as IonIconName[];
