// Transcribes the kit's ions-icons-inline.js sprite into a typed module so the
// React binding carries the same paths without a cross-file <use> reference.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pkg = join(here, '..');
// In the prototype-kit repo the kit is the parent directory; in the portable
// kit its inputs are vendored into ./kit.
const kit = existsSync(join(pkg, 'kit', 'foundations')) ? join(pkg, 'kit') : join(pkg, '..');

const src = readFileSync(join(kit, 'foundations', 'ions-icons-inline.js'), 'utf8');
const re = /<symbol id="([a-z0-9-]+)" viewBox="([^"]+)">([\s\S]*?)<\/symbol>/g;

const icons = {};
let m;
while ((m = re.exec(src))) icons[m[1]] = { viewBox: m[2], body: m[3].trim() };

const names = Object.keys(icons);
if (!names.length) throw new Error('no symbols parsed from ions-icons-inline.js');

const out = `// GENERATED by scripts/build-icons.mjs from ../foundations/ions-icons-inline.js
// Do not edit by hand; re-run \`npm run build:icons\` instead.

export interface IonIconDef {
  viewBox: string;
  body: string;
}

export const ionIcons = ${JSON.stringify(icons, null, 2)} as const satisfies Record<string, IonIconDef>;

/** Every icon id shipped by the Ions catalogue. */
export type IonIconName = keyof typeof ionIcons;

export const ionIconNames = ${JSON.stringify(names, null, 2)} as IonIconName[];
`;

mkdirSync(join(pkg, 'src', 'foundations'), { recursive: true });
writeFileSync(join(pkg, 'src', 'foundations', 'icons.generated.ts'), out);
console.log(`icons: ${names.length} symbols -> src/foundations/icons.generated.ts`);
